name: catbob Code CI
on:
  workflow_call:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: [16.x]

    name: test/${{ matrix.node-version }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: npm ci

      - name: Unit Tests
        run: npm test

      - name: Prettier
        run: npx prettier --check './src/' './tests'
