name: deploy to ec2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  use-test:
    uses: tizayi/catbob/.github/workflows/code.yml@main
  deploy:
    name: Deploy to EC2 on main branch push
    needs: use-test
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.USER_NAME }}/catbob
            bash .github/scripts/container-manager.sh restart
