name: deploy to ec2
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/catbob"
          EXCLUDE: "/node_modules/"
          SCRIPT_AFTER: |
            bash ./.github/scripts/container-manager.sh restart
